export const ActionTypes = {
    SET_CURRENT_QUESTION_SCHEMA: `SET_CURRENT_QUESTION_SCHEMA`,
    SET_TRIVIA_ID: `SET_TRIVIA_ID`,
    SET_CORRECT_ANSWERS: `SET_CORRECT_ANSWERS`,
    SET_CURRENT_ANSWER_STATUS: `SET_CURRENT_ANSWER_STATUS`,
    SET_LOCAL_SCORE: `SET_LOCAL_SCORE`,
    RESET_LOCAL_SCORE: `RESET_LOCAL_SCORE`
}