export const ActionTypes = {
    SET_ROUTER: `SET_ROUTER`,
    SET_WORKFLOW_DEFINITION: `SET_WORKFLOW_DEFINITION`,
    SET_CURRENT_STEP_ID: `SET_CURRENT_STEP_ID`,
    SET_CURRENT_STEP: `SET_CURRENT_STEP`,
    SET_CURRENT_PATH: `SET_CURRENT_PATH`,
    SET_TOTAL_QUESTIONS: `SET_TOTAL_QUESTIONS`
}