export const ActionTypes = {
    SET_ROUTER: `SET_ROUTER`,
    SET_WORKFLOW_DEFINITION: `SET_WORKFLOW_DEFINITION`,
    SET_CURRENT_STEP_ID: `SET_CURRENT_STEP_ID`,
    SET_CURRENT_STEP: `SET_CURRENT_STEP`
}