service: TriviaApp

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true
  tracing:
    lambda: true # optional, enables tracing for all functions (can be true (true equals 'Active') 'Active' or 'PassThrough')
  environment:
    DYNAMODB_TABLE:
      Ref: TriviaDynamoDbTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
      Resource: "*"

functions:
  listTrivia:
    handler: listTriviaFunction.handler # required, handler set in AWS Lambda
    name: ${opt:stage, self:provider.stage, 'dev'}-listTrivia # optional, Deployed Lambda name
    description: Returns a list of all trivia available
    events:
      - http:
          path: /v1/trivia
          method: get
          memorySize: 128
          cors:
            origin: '*'
            
  workflow:
    handler: workflowFunction.handler
    name: ${opt:stage, self:provider.stage, 'dev'}-workflowTrivia
    description: Returns current workflow with steps
    events:
      - http:
          path: /v1/trivia/{triviaId}
          method: get
          memorySize: 128
          cors:
            origin: '*'
          
  questionTrivia:
    handler: questionTriviaFunction.handler
    name: ${opt:stage, self:provider.stage, 'dev'}-questionTrivia
    description: Returns current questionSchema
    events:
      - http:
          path: /v1/trivia/{triviaId}/{questionId}
          method: get
          memorySize: 128
          cors:
            origin: '*'

  questionAnswer:
    handler: questionAnswerFunction.handler
    name: ${opt:stage, self:provider.stage, 'dev'}-answerTrivia
    description: Returns correct answers with user answers
    events:
      - http:
          path: /v1/trivia/{triviaId}/{questionId}
          method: post
          memorySize: 128
          cors:
            origin: '*'
resources:
  Resources:
    TriviaDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: primary_key
            AttributeType: S
          -
            AttributeName: secondary_key
            AttributeType: S
        KeySchema:
          -
            AttributeName: primary_key
            KeyType: HASH
          -
            AttributeName: secondary_key
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

